### ISSUE TITLE
List on the IPFS Client Libraries table?

### ISSUE THREAD

**Issue by daviddias** [ogeagla/clojure-ipfs-api#1]
Hi @ogeagla! Are you actively developing this client library? Wanna list it at https://github.com/ipfs/ipfs#api-client-libraries ?

**Comment by ogeagla** [comment]
@diasdavid I haven't been working on this lately but I'd like to get some basic functionality in before having it listed. Is this coming from active interest in a Clojure client?

**Comment by ogeagla** [comment]
Actually now that I notice that some projects have `0%` complete, you may go ahead and list it with that as `0%` for `Completeness`, and that'll put some fire under me to get working on it.  Thanks much for reaching out!
